CREATE TABLE STUDENT_SHEDLOCK
(
    NAME       VARCHAR(64),
    LOCK_UNTIL TIMESTAMP(3) NULL,
    LOCKED_AT  TIMESTAMP(3) NULL,
    LOCKED_BY  VARCHAR(255),
    CONSTRAINT STUDENT_SHEDLOCK_PK PRIMARY KEY (NAME)
);
