package ca.bc.gov.educ.api.student.constant;

public enum EventOutcome {
  STUDENT_FOUND,
  STUDENT_NOT_FOUND,
  STUDENT_CREATED,
  STUDENT_UPDATED,
  STUDENT_TWINS_ADDED,
  STUDENT_TWINS_DELETED,
  STUDENT_ALREADY_EXIST
}
