INSERT INTO STUDENT_HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                           EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('GMP', 'GMP', 'Change via GMP, ID reviewed and DEMOG_CODE update', 14, to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/OMISHRA', SYSDATE, 'IDIR/OMISHRA',SYSDATE);

INSERT INTO STUDENT_HISTORY_ACTIVITY_CODE (HISTORY_ACTIVITY_CODE, LABEL, DESCRIPTION, DISPLAY_ORDER, EFFECTIVE_DATE,
                                           EXPIRY_DATE, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE)
VALUES ('UMP', 'UMP', 'Change via UMP, ID reviewed and DEMOG_CODE update', 15, to_date('2020-01-01', 'YYYY-MM-DD'),
        to_date('2099-12-31', 'YYYY-MM-DD'), 'IDIR/OMISHRA', SYSDATE, 'IDIR/OMISHRA',SYSDATE);
