--Add Columns to STUDENT
ALTER TABLE STUDENT ADD (
    POSTAL_CODE VARCHAR2(7),
    LOCAL_ID VARCHAR2(12),
    GRADE VARCHAR2(2),
    MINCODE VARCHAR2(8)
);

--Modify Columns in STUDENT to lengthen names
ALTER TABLE STUDENT MODIFY (
     LEGAL_FIRST_NAME VARCHAR2(255);
     LEGAL_LAST_NAME VARCHAR2(255);
     USUAL_FIRST_NAME VARCHAR2(255);
     USUAL_LAST_NAME VARCHAR2(255);
);
