DROP TABLE API_STUDENT.STUDENT_MERGE_DIRECTION_CODE CASCADE CONSTRAINTS ;
DROP TABLE API_STUDENT.STUDENT_MERGE_SOURCE_CODE CASCADE CONSTRAINTS ;
DROP TABLE API_STUDENT.STUDENT_TWIN_REASON_CODE CASCADE CONSTRAINTS ;
DROP TABLE API_STUDENT.STUDENT_MERGE CASCADE CONSTRAINTS ;
DROP TABLE API_STUDENT.STUDENT_TWIN CASCADE CONSTRAINTS ;
